server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: recon-producer-app
  lifecycle:
    timeout-per-shutdown-phase: 30s

aws:
  secrets:
    enabled: ${AWS_SECRETS_ENABLED:false}
    region: ${AWS_REGION:us-east-1}
    name: ${AWS_SECRET_NAME:local}

ibm:
  mq:
    queue-manager: ${MQ_QMGR:QM1}
    channel: ${MQ_CHANNEL:DEV.APP.SVRCONN}
    conn-name: ${MQ_CONN_NAME:localhost(1414)}
    user: ${MQ_USER:app}
    password: ${MQ_PASSWORD:pass}

recon:
  input-queue: ${RECON_INPUT_QUEUE:DEV.QUEUE.1}
  producer-tps: ${PRODUCER_TPS:1}
  producer-interval-ms: ${PRODUCER_INTERVAL_MS:10000}
  invalid-percent: ${INVALID_PERCENT:0}
  message-source: ${MESSAGE_SOURCE:recon-producer-app-local}

management:
  tracing:
    enabled: ${TRACING_ENABLED:false}
    sampling:
      probability: ${OTEL_TRACES_SAMPLER_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://jaeger-collector.observability.svc.cluster.local:4318/v1/traces}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
