apiVersion: v1
kind: ServiceAccount
metadata:
  name: recon-app-sa
  namespace: recon-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::860510876120:role/recon-platform-secrets-role

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-mq-sa
  namespace: recon-platform
