apiVersion: v1
kind: ConfigMap
metadata:
  name: ibm-mq-config
  namespace: recon-platform
data:
  20-recon-queues.mqsc: |
    DEFINE QLOCAL('RECON.IN') REPLACE DEFPSIST(YES) BOTHRESH(3) BOQNAME('RECON.BACKOUT')
    DEFINE QLOCAL('RECON.RETRY') REPLACE DEFPSIST(YES)
    DEFINE QLOCAL('RECON.BACKOUT') REPLACE DEFPSIST(YES)
    DEFINE QLOCAL('RECON.REPLAY') REPLACE DEFPSIST(YES)
    DEFINE QLOCAL('SYSTEM.DEAD.LETTER.QUEUE') REPLACE DEFPSIST(YES)
    ALTER QMGR DEADQ('SYSTEM.DEAD.LETTER.QUEUE')
    DEFINE CHANNEL('DEV.APP.SVRCONN') CHLTYPE(SVRCONN) TRPTYPE(TCP) REPLACE
    SET CHLAUTH('DEV.APP.SVRCONN') TYPE(BLOCKUSER) USERLIST('nobody')
    SET AUTHREC OBJTYPE(QMGR) PRINCIPAL('app') AUTHADD(CONNECT,INQ,DSP)
    SET AUTHREC PROFILE('RECON.IN') OBJTYPE(QUEUE) PRINCIPAL('app') AUTHADD(PUT,GET,BROWSE,INQ,DSP)
    SET AUTHREC PROFILE('RECON.RETRY') OBJTYPE(QUEUE) PRINCIPAL('app') AUTHADD(PUT,GET,BROWSE,INQ,DSP)
    SET AUTHREC PROFILE('RECON.BACKOUT') OBJTYPE(QUEUE) PRINCIPAL('app') AUTHADD(PUT,GET,BROWSE,INQ,DSP,PASSALL)
    SET AUTHREC PROFILE('RECON.REPLAY') OBJTYPE(QUEUE) PRINCIPAL('app') AUTHADD(PUT,GET,BROWSE,INQ,DSP)
    SET AUTHREC PROFILE('SYSTEM.DEAD.LETTER.QUEUE') OBJTYPE(QUEUE) PRINCIPAL('app') AUTHADD(PUT,GET,BROWSE,INQ,DSP,PASSALL)
    REFRESH SECURITY TYPE(CONNAUTH)
    REFRESH SECURITY TYPE(AUTHSERV)
